server:
  port: 8083

spring:
  application:
    name: enterprise-aws-devops-platform

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  